FROM mysql:8.0.13

ENV MYSQL_HOST=crb-app-mysql
ENV MYSQL_PORT=3307
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=fci_regulation_bias
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

#COPY ./init-db.sql /docker-entrypoint-initdb.d/

EXPOSE 3307