server:
  address: 0.0.0.0
  port: 8098
  connection-timeout: 5s

  #ssl:
  #  key-store: keystore.p12
  #  key-store-password: springboot
  #  keyStoreType: PKCS12
  #  keyAlias: tomcat

application:
  security:
    jwt:
      secret-key: A37DD6A898EFAC35DCEC7BA1A9FCF
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
#
#spring:
#  application:
#    name: calculate-regulation-disarrangement
#  datasource:
#    url: jdbc:mysql://localhost:3306/fci_regulation_bias?createDatabaseIfNotExist=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false&characterEncoding=UTF-8
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    initialize: true
#    initialization-mode: always
#    hikari:
#      connection-timeout: 6000
#      initialization-fail-timeout: 0
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        enable_lazy_load_no_trans: true
  #h2:
  #  console:
  #    enabled: true